name: Terraform apply

on:
  push:
    branches: [main]
    paths:
      - 'environment/dev/**' 

jobs:
  build:
    runs-on: ubuntu-latest 
    environment: dev
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Terraform init
        run: |
          terraform init --backend-config=environment/dev/backend.conf

      - name: Terraform Fmt
        run: |
          terraform fmt

      - name: Terraform validate
        run: |
          terraform validate

      - name: Terraform apply
        run: |
          terraform apply --var-file=environment/dev/dev.tfvars -auto-approve



          
